jobs:
  build:
    docker:
      - image: muradakh/ocaml-cil-npm:0

    steps:
      - checkout

      - run: ln -s /root/.opam/4.05.0/bin/cilly /usr/bin/cilly 
      - run:
          name: Install npm dependencies
          command: npm i

      - run:
          name: run tests
          command: npm test